import fs from "node:fs";
import path from "node:path";

const root = path.resolve(import.meta.dirname, "..");
const sources = {};

// Route every bundled RBXScriptSignal connection through the runtime tracker.
// Exported sources only use plain property chains plus zero/one-level method
// calls as Connect receivers (for example RunService.Stepped or
// value:GetPropertyChangedSignal("Value")).
function instrumentConnections(source) {
  const receiver = /([A-Za-z_]\w*(?:\.[A-Za-z_]\w*)*(?::[A-Za-z_]\w*\([^()\r\n]*\))?(?:\.[A-Za-z_]\w*)*):Connect\(/gu;
  return source.replace(receiver, "VRFConnect($1, ");
}

function walk(directory) {
  for (const entry of fs.readdirSync(directory, { withFileTypes: true })) {
    const file = path.join(directory, entry.name);
    if (entry.isDirectory()) walk(file);
    else if (entry.name.endsWith(".lua")) {
      const relative = path.relative(path.join(root, "src"), file).replaceAll("\\", "/");
      if (relative === "runtime/Bootstrap.lua") continue;
      let key = relative.replace(/\.client\.lua$|\.server\.lua$|\.lua$/u, "");
      sources[key] = instrumentConnections(fs.readFileSync(file, "utf8"));
    }
  }
}

walk(path.join(root, "src"));
const manifest = JSON.parse(fs.readFileSync(path.join(root, "manifest", "export.json"), "utf8"));

function longString(value) {
  let equals = "";
  while (value.includes(`]${equals}]`)) equals += "=";
  return `[${equals}[${value}]${equals}]`;
}

function lua(value) {
  if (value === null || value === undefined) return "nil";
  if (typeof value === "string") return JSON.stringify(value);
  if (typeof value === "number" || typeof value === "boolean") return String(value);
  if (Array.isArray(value)) return `{${value.map(lua).join(",")}}`;
  return `{${Object.entries(value).map(([key, item]) => `[${JSON.stringify(key)}]=${lua(item)}`).join(",")}}`;
}

const sourceTable = Object.entries(sources)
  .map(([key, value]) => `[${JSON.stringify(key)}]=${longString(value)}`)
  .join(",\n");
const bootstrap = fs.readFileSync(path.join(root, "src", "runtime", "Bootstrap.lua"), "utf8");
const output = `-- Generated by scripts/build.mjs; do not edit by hand.\nlocal Package={Sources={${sourceTable}},Manifest=${lua(manifest)}}\n${bootstrap}\n`;

fs.mkdirSync(path.join(root, "dist"), { recursive: true });
fs.writeFileSync(path.join(root, "dist", "vrftoprs.lua"), output);
console.log(`Built dist/vrftoprs.lua with ${Object.keys(sources).length} sources.`);
