local _ = _G;
local l_game_0 = game;
local _ = script;
local _ = getfenv;
local _ = setfenv;
local _ = workspace;
local _ = getmetatable;
local _ = setmetatable;
local _ = loadstring;
local _ = coroutine;
local _ = rawequal;
local _ = typeof;
local _ = print;
local _ = math;
local _ = warn;
local _ = error;
local _ = pcall;
local _ = ypcall;
local _ = xpcall;
local _ = select;
local _ = rawset;
local _ = rawget;
local _ = ipairs;
local l_pairs_0 = pairs;
local _ = next;
local _ = Rect;
local _ = Axes;
local _ = os;
local _ = tick;
local _ = Faces;
local _ = unpack;
local _ = string;
local _ = Color3;
local _ = newproxy;
local _ = tostring;
local _ = tonumber;
local _ = Instance;
local _ = TweenInfo;
local l_BrickColor_0 = BrickColor;
local _ = NumberRange;
local _ = ColorSequence;
local _ = NumberSequence;
local _ = ColorSequenceKeypoint;
local _ = NumberSequenceKeypoint;
local _ = PhysicalProperties;
local _ = Region3int16;
local _ = Vector3int16;
local _ = elapsedTime;
local l_require_0 = require;
local l_table_0 = table;
local _ = type;
local _ = wait;
local l_Enum_0 = Enum;
local _ = UDim;
local _ = UDim2;
local _ = Vector2;
local l_Vector3_0 = Vector3;
local _ = Region3;
local _ = CFrame;
local l_Ray_0 = Ray;
local _ = delay;
local v69 = {};
local _ = l_game_0:GetService("Debris");
local l_ReplicatedStorage_0 = l_game_0:GetService("ReplicatedStorage");
local l_UserInputService_0 = l_game_0:GetService("UserInputService");
local l_LocalPlayer_0 = l_game_0:GetService("Players").LocalPlayer;
local l_Character_0 = l_LocalPlayer_0.Character;
if not l_Character_0 or not l_Character_0.Parent then
    l_Character_0 = l_LocalPlayer_0.CharacterAdded:wait();
end;
local l_Humanoid_0 = l_Character_0:WaitForChild("Humanoid");
local l_CurrentCamera_0 = l_game_0:GetService("Workspace").CurrentCamera;
local _ = l_ReplicatedStorage_0:WaitForChild("Remotes");
local l_ClientModules_0 = game:GetService("Players").LocalPlayer:WaitForChild("PlayerScripts"):WaitForChild("ClientModules");
local v79 = l_require_0(l_ClientModules_0:WaitForChild("llllIllIllIIIlllIIIIlIllIIIlIIlII"));
local _ = l_require_0(l_ClientModules_0:WaitForChild("llIIllIIlllIIIIIlIIIIIIlIlIlIIIlI"));
local _ = l_require_0(l_ClientModules_0:WaitForChild("IlllIlIIIlIlllIIlIlIlIllllIIllIII"));
local _ = v79:GetLimbs(l_Character_0, l_Humanoid_0);
local _ = l_Humanoid_0:LoadAnimation(l_LocalPlayer_0:WaitForChild("PlayerGui"):WaitForChild("Animations").PassTool.MarkPointAnim.RightMarkPoint);
local v84 = false;
local v85 = {};
for _, v87 in l_pairs_0(l_game_0:GetService("Workspace"):WaitForChild("Pitch"):GetChildren()) do
    if v87.Name ~= "InvisibleWalls" then
        l_table_0.insert(v85, v87);
    end;
end;
v69.Activate = function(_, v89, _) --[[ Line: 123 ]]
    if v89 == l_Enum_0.UserInputState.Begin and v79:CheckState() and not v79:CheckDebounce() and not v84 --[[and (not (l_LocalPlayer_0.TeamColor ~= l_BrickColor_0.new("Really blue") and l_LocalPlayer_0.TeamColor ~= l_BrickColor_0.new("Bright blue") and l_LocalPlayer_0.TeamColor ~= l_BrickColor_0.new("Camo")) or l_LocalPlayer_0.TeamColor == l_BrickColor_0.new("Bright green"))]] then
        v84 = true;
        local l_l_UserInputService_0_MouseLocation_0 = l_UserInputService_0:GetMouseLocation();
        local v92 = l_CurrentCamera_0:ViewportPointToRay(l_l_UserInputService_0_MouseLocation_0.X, l_l_UserInputService_0_MouseLocation_0.Y);
        local v93 = l_Ray_0.new(v92.Origin, v92.Direction * 1000);
        local l_PartOnRayWithWhitelist_0, v95 = l_game_0:GetService("Workspace"):FindPartOnRayWithWhitelist(v93, v85);
		if l_PartOnRayWithWhitelist_0 then
            v79:MakeMarker(l_Vector3_0.new(v95.X, v95.Y, v95.Z), l_LocalPlayer_0.Name);
            task.wait(2);
        end;
        v84 = false;
    end;
end;
return v69;
